### ISSUE TITLE
Enhance Compatibility by Supporting class Attribute Alongside className

### ISSUE THREAD

**Issue by roonie007** [doinki/eslint-plugin-trim#2]
I've been working with this plugin and noticed it exclusively utilizes the `className` attribute. 

Could you extend the plugin's functionality to support the `class` attribute as well ? 

This enhancement would significantly broaden the plugin's compatibility, making it more versatile and applicable to a wider range of JavaScript frameworks and libraries that rely on the class attribute.

**Comment by doinki** [comment]
@roonie007 
Thanks for using this plugin.

I think it would be better to be able to set the attributes as options as you said.
But I'm busy with my work, so it will be difficult to add the feature right away. I'll try to add the feature this month.

**Comment by doinki** [comment]
@roonie007 

```js
module.exports = {
  plugins: ['trim'],
  rules: {
    'trim/class-name': ['error', { attributes: ['class', 'className'] }]
  }
};
```

I changed this to be customisable via the attributes option, which defaults to ['class', 'className'].

**Comment by roonie007** [comment]
Awesome, thanks a lot 🙏
